algoritmo "Departamento de Transito"
var
   Anoatual, Nasc, Idade: inteiro

inicio
      Escreval ("Ano atual: ")
      Leia (Anoatual)
      Escreva ("Ano de nasc: ")
      Leia (Nasc)
      Idade <- Anoatual - Nasc
      EscrevaL ("sua idade e " , Idade)
      Se (Idade >= 18) e (Idade >= 18) entao
      EscrevaL ("Parabéns, voce esta APTO ")
      Senao
      Escreva ("Que pena, voce esta INAPTO ")
      FimSe






fimalgoritmo
